### PR TITLE
fix: dex not fond 404

### PR DESCRIPTION
**Pull request by EightDoor**

### CODE REVIEW

**Comment by takxlz** [comment]
export { default as SQLQueryBuilder } from "https://raw.githubusercontent.com/aghussb/dex/master/mod.ts";

The above url worked fine.(#209)

**Comment by EightDoor** [comment]
@takxlz thank you

**Comment by eEQK** [comment]
I got this error using @EightDoor fork:
```ts
export {
  Database,
  DataTypes,
  Model,
  SQLite3Connector,
} from "https://raw.githubusercontent.com/EightDoor/denodb/master/mod.ts";
```
```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/dex@1.0.2/lib/deps/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/x/dex@1.0.2/lib/deps/path/posix.ts:433:18

Found 2 errors.
```

I assume it's because dex has to be upgraded from 1.0.2 to >1.2.0 (as indicated in dex README)

@takxlz version works fine:
```ts
export {
  Database,
  DataTypes,
  Model,
  SQLite3Connector,
} from "https://raw.githubusercontent.com/takxlz/denodb/master/mod.ts";
```

**Comment by antoniogamiz** [comment]
Any update on this?

**Comment by eveningkid** [comment]
Hello EightDoor,

Thank you so much for doing a PR for this!

I clearly haven't checked my notifications for a while which explains the delay, thanks for your patience really.

I just pushed to master a commit that should fix all this situation.

It'd be better if we follow along the progress on #209 for now.

I'll handle this, no worries really!

Have a great day :)

**Pull request closed without merging**
