### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by techtastet**
Hi !

To keep a code consistent with the formatting of `Deno fmt`, it would be good to integrate a github action which will check if the code of a PR is well formatted in order to indicate to the person if his code is ready or not to be merge  😄 

So i did it in this PR 😉 

Hoping to help

### CODE REVIEW

**Comment by eveningkid** [comment]
Hi again Thomas,

...wow it even reorders exports/imports by name! That's very cool!

I will be picky on this one, just to keep things clean, could you `git rebase` this a little bit so that it has only two commits max (one for the new file, one for the formatting). You can also make it just one, that is up to you!

Thank you really for helping out, I really appreciate it. This will be for the better! :)

Keep in touch

**Review by eveningkid — CHANGES_REQUESTED** [review]
We need a `git rebase` before merging...which is what we all hate doing I know!

**Comment by techtastet** [comment]
> We need a `git rebase` before merging...which is what we all hate doing I know!

Okay, I tried many times but i cant get this to work with github PR can you help me haha?

**Comment by eveningkid** [comment]
@techtastet would [this tutorial](https://christoph-rumpel.com/2015/05/clean-up-your-commits-for-a-pull-request) help? You just need to squash your commits and force push your changes :)

**Comment by techtastet** [comment]
+ I added a fix to this PR on the "created_at" field which was incorrectly updating and which created an error 😄

**Comment by eveningkid** [comment]
Hi Thomas,

I am sorry it's been years!!

I don't know why we make this harder than it should.

1) Let's close this PR
2) Create another one, paste `.github/workflows/deno.yml`, commit, push
3) Let's merge this!!

Let me know if you want me to do it, I was hoping there could have your name on it as **you** did the work! 😄

**Pull request closed without merging**
